# Generated by Django 2.0.8 on 2018-08-30 07:43

from django.db import migrations
import wagtailmd.utils


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('blog', '0004_postpage_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('taggit.tag',),
        ),
        migrations.AlterField(
            model_name='postpage',
            name='body',
            field=wagtailmd.utils.MarkdownField(),
        ),
    ]
